#!/usr/bin/env bash
# Production host only. Generates caddy/tailscale-cert.cron (gitignored —
# bakes in this host's absolute repo path, which can't be committed) and
# symlinks it into /etc/cron.d, so the schedule stays defined in this repo
# instead of a bare `crontab -e` edit. Re-run after moving the repo or
# changing the schedule below.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CRON_FILE="$REPO_DIR/caddy/tailscale-cert.cron"
CRON_LINK="/etc/cron.d/apollo-tailscale-cert"

cat >"$CRON_FILE" <<EOF
# Generated by caddy/install-cron.sh — do not edit by hand, re-run that
# script instead (e.g. after moving this repo).
0 3 * * 0 root cd $REPO_DIR && ./caddy/renew-tailscale-cert.sh >>/var/log/apollo-tailscale-cert-renew.log 2>&1
EOF
chmod 644 "$CRON_FILE"

sudo ln -sf "$CRON_FILE" "$CRON_LINK"

echo "Installed: $CRON_LINK -> $CRON_FILE"
echo
echo "Contents:"
cat "$CRON_FILE"
echo
echo "Some cron builds (notably some Debian/Ubuntu cron packages) silently ignore"
echo "symlinks or non-root-owned targets in /etc/cron.d. Verify it's actually"
echo "picked up — e.g. temporarily change the schedule above to '* * * * *',"
echo "wait a minute, check /var/log/apollo-tailscale-cert-renew.log, then set it"
echo "back and re-run this script. If it never fires, replace the symlink with a"
echo "real copy instead:"
echo "  sudo rm \"$CRON_LINK\" && sudo cp \"$CRON_FILE\" \"$CRON_LINK\" && sudo chown root:root \"$CRON_LINK\""
