services:
  aiometadata:
    image: ghcr.io/cedya77/aiometadata:3.1.0
    container_name: aiometadata
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    pids_limit: 512
    environment:
      HOST_NAME: "${HOST_NAME}"
      DATABASE_URI: "sqlite://addon/data/db.sqlite"
      REDIS_URL: "redis://:${REDIS_PASSWORD:?}@redis:6379"
      ADMIN_KEY: "${ADMIN_KEY}"
      ADDON_PASSWORD: "${ADDON_PASSWORD}"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - data:/app/addon/data
    networks:
      - apollo

volumes:
  data:

networks:
  apollo:
    external: true
